import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arnifi | Online Will Generator ",
  description: "Generated by create next app",
  keywords: "nextjs, next, javascript",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <link rel="icon" href="./favicon.ico" sizes="any" />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
